name: pipeline-env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - perl=5.20
  - perl-app-cpanminus
  - perl-dbd-sqlite
  - perl-dbd-mysql
  - python=3.5.2
  - python-igraph
  - pip
  - pip:
    - numpy==1.13.3
    - multiqc==1.2
    - coveralls
    - html5lib
    - lxml
    - bs4
    - pandas==0.21.0
    - sqlalchemy
    - pymysql
    - slackclient
    - asana
    - matplotlib
    - unittest2
    - jinja2
    - gviz_api
    - xlrd
    - jsonschema
    - pysam==0.14.1
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - louvain
    - scanpy
