name: pipeline-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5.2
  - python-igraph
  - pip
  - pip:
    - coveralls
    - html5lib
    - lxml
    - bs4
    - sqlalchemy
    - pymysql
    - slackclient
    - asana
    - matplotlib
    - unittest2
    - jinja2
    - gviz_api
    - xlrd
    - jsonschema
    - pysam==0.14.1
    - seaborn
    - scikit-learn
    - statsmodels
    - multiqc==1.4
    - numba
    - louvain
    - scanpy
    - pandas==0.23.0
    - numpy==1.14
    - bioservices
