channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - python=3.5.2
  - python-igraph==0.7.1.post6
  - louvain==0.6.1
  - pip
  - pip:
    - coveralls==1.3.0
    - html5lib==1.0.1
    - lxml==4.2.4
    - bs4==0.0.1
    - SQLAlchemy==1.2.11
    - PyMySQL==0.9.2
    - slackclient==1.2.1
    - asana==0.8.0
    - matplotlib==2.2.3
    - unittest2==1.1.0
    - Jinja2==2.10
    - gviz-api==1.9.0
    - xlrd==1.1.0
    - jsonschema==2.6.0
    - seaborn==0.9.0
    - scikit-learn==0.19.2
    - scipy==1.1.0
    - statsmodels==0.9.0
    - multiqc==1.7
    - numba==0.39.0
    - pandas==0.23.0
    - numpy==1.14.0
    - bioservices==1.5.2
    - scanpy==1.2.2
  - r-base==3.4.1
  - bioconductor-edger
