site_name: IGF Pipelines
pages:
  - 'Home': 'index.md'
  - Pipeline setup
      - 'Pipeline source code and environment': 'scripts/env.md'
  - Scripts:
      - 'Find new sequencing runs in server': 'scripts/find_new_seqrun_and_prepare_md5.md'
  - Database operations: 
      - 'Clean and rebuild database': 'scripts/clean_and_rebuild_database.md'
      - 'Load platform data to database': 'scripts/load_platform_data.md'
      - 'Load pipeline data to database': 'scripts/load_pipeline_data.md'
formats:
    - pdf
