site_name: IGF Pipelines
pages:
  - 'Home': 'index.md' 
  - Scripts:
      - 'Find new sequencing runs in server': 'scripts/find_new_seqrun_and_prepare_md5.md'
formats:
    - pdf
theme: bootstrap
requirements_file: requirements.txt
