site_name: IGF Pipelines
pages:
    - 'Introduction': 'index.md' 
    - 'Scripts': 'scripts/index.md'
    - 'Scripts/Find new sequencing run': 'scripts/find_new_seqrun_and_prepare_md5.md'
formats:
    - pdf
